### ISSUE TITLE
READMEとwikiについて

### ISSUE THREAD

**Issue by taku300** [taku300/FWA#22]
<sub> ドキュメント管理</sub>
--
ドキュメントを全てGoogle Driveで管理している。
READMEには開発者用の情報を記載する（環境構築やバージョン情報）
wikiは概要や運用方法等について記載する。
ネットを見る限りの情報で以下の分類を考えている。

>[README.md：開発者向け、Wiki：利用者向け](https://qiita.com/suzuki-hoge/items/1d6022cca177e2d96bb5)
>[README.md：簡単な使い方、Wiki：詳細な使い方](https://gist.github.com/manabuyasuda/f449b313970c7a51b655)
<br>

<sub> マークアップ記法</sub>
--
マーグダウン記法を常に使うように意識したい。READMEとwikiに限らず、issueなども全てこの記法で書くことを意識して実際の開発に近づけるように工夫する。

>[基本的な書き方とフォーマットの構文](https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
>[GitHub「Markdown記法」と「折りたたみ」で読みやすさアップ](https://www.wakuwakubank.com/posts/861-git-markdown/)
>[テーブルの書き方1](https://notepm.jp/help/markdown-table)
>[テーブルの書き方2](https://www.sejuku.net/blog/77323)
>[TUDO作成](https://docs.github.com/ja/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists)
<br>

<sub> issueの活用</sub>
--
課題が発生したときはissueを積極的に活用していく。
またどのような設計で開発を行うか等の調査内容も、それが発生した時点でissueを作成しそこで議論する

**メリット**
- Labelでジャンル分けできる
- Milestone等でスケージュールの管理が行える
- Assigneeで担当を割り振れる
- projectでタスク管理ができる

<sub> parjectの活用</sub>
--
プロジェクトとissueを結びつけることができる。使い方としては作ったissueの優先順位をつけることことに使いたい。タスク管理は別途ガントチャートを使っている。

>[チーム開発を変える「GitHub」とは？〜Issuesの使い方〜](https://seleck.cc/647)
>[GitHubのデフォルトラベルを和訳 + 絵文字付加](https://crieit.net/posts/GitHub-5f79db931e76f)
>[GitHubのproject機能とは](https://style.potepan.com/articles/33624.html)

**Comment by taku300** [comment]
- このプロジェクトで使用するGem(Rubyのライブラリ)をインストール
```bash
$ bundle install --path vendor/bundle
```

READMEこんな書き方のがいい以下も

**Comment by t-ookuma** [comment]
ひとまずこの書き方でOK
開発していく上でブラッシュアップは必須。
