### ISSUE TITLE
画面上部のタイトルの切り替え

### ISSUE THREAD

**Issue by taku300** [taku300/FWA#26]
二つの方法を考えた

１、コンポーネントに代入して管理する。

２、レイアウトのファイルにconfigを作ってphpで管理する。
　具体的にはコントローラーとアクション名によりswichぶんで場合分けを行いタイトルを取得
　コントローラ、アクションの取得に関してはUillを用いてUtil::getcontrollerのような形で呼び出す。
　Route::current()->controllerでとって来れそう。

**Comment by taku300** [comment]
viewで変数をいつでも使えるようにする方法

https://zakkuri.life/laravel-global-variable/
https://minory.org/laravel-view-share.html

**Comment by t-ookuma** [comment]
TitleCommon.php
コントローラー名抽出の共通処理

public static function getTitle($key)
{
    $controller = explode("@", Route::currentRouteAction());
    $controllerName = explode('\\', $controller[0]);
    $titleKey = mb_substr($controllerName[3], 0, -10);

    return TitleConst::TITLE_LIST[$titleKey][$key];
}


TopTitleServiceProvider.php
タイトル、サブタイトル定義

// タイトル
app()->bind('en', function () {
    return TitleCommon::getTitle('en');
});

// サブタイトル
app()->bind('ja', function () {
    return TitleCommon::getTitle('ja');
});



Controller.php
タイトル、サブタイトル取得

// タイトル
$en = app()->make('en');
// サブタイトル
$ja = app()->make('ja');

**Comment by t-ookuma** [comment]
張り方へたくそだから頑張って確認してほしい

急いだからコードもうちょい減らせるかも

**Comment by taku300** [comment]
ビューコンんポーザー
enn.dev/yukihaga/articles/4eaf40c9b0419e

Bootメソッド
では、[ビューコンポーサ](https://readouble.com/laravel/8.x/ja/views.html#view-composers)をサービスプロバイダで登録する必要がある場合は、どうすればよいのでしょうか？　bootメソッドの中で行ってください。このメソッドは、他の全サービスプロバイダが登録し終えてから呼び出されます。つまりフレームワークにより登録された、他のサービスすべてにアクセスできるのです。
https://readouble.com/laravel/8.x/ja/providers.html

**Comment by taku300** [comment]
view::composerで返すときに変数ごとに処理を行っているので、その部分をひとまとめて、view側でキーを指定するように変える。

**Comment by taku300** [comment]
SEOの観点からタイトルタグを画面の役割に応じて動的に切り替える必要があるみたい。

### 参考
[タイトルタグの動的な切り替え](https://note.com/koushikagawa/n/n33a561590aee)

**Comment by taku300** [comment]
行こう以下のissueへ移行
https://github.com/taku300/FWA/issues/72
