### ISSUE TITLE
Services, Libs, Consts使用方法

### ISSUE THREAD

**Issue by t-ookuma** [taku300/FWA#35]
---------- Services ----------

・階層構造
　→App\Servicesディレクトリに配置
・命名
　→SampleService.php ※Sampleはモデル名と対応
・処理
　→基本的にCRUD処理のうちCUDのみ ※Rはモデルで成形

---------- Libs ----------

・階層構造
　→App\Libsディレクトリに配置
・命名
　→Sample.php ※Sampleは処理がわかるように命名する（GetTitleName.php等）
・処理
　→共通処理のみ

---------- Consts ----------

・階層構造
　→App\Constsディレクトリに配置
・命名
　→SampleConst.php ※Sampleは処理がわかるように命名する（TitleNameConst.php等）
・定義
　→定数定義 ※データの変動がほぼないものかつ繰り返し使うもののみ

**Comment by taku300** [comment]
これで行こうインターフェイス入れるかはあとから考えて、とりあえず作っていく方針で
